-- https://neovim.io/doc/user/options.html

for key, val in pairs
{
    autowrite = true,
    clipboard = "unnamedplus",
    completeopt = "menu,preview",
    confirm = true,
    cursorline = true,
    expandtab = true,
    ignorecase = true,
    inccommand = "nosplit",
    laststatus = 0,
    -- list = true,
    mouse = "a",
    number = true,
    pumblend = 10,
    pumheight = 10,
    relativenumber = true,
    scrolloff = 4,
    shiftround = true,
    shiftwidth = 2,
    shortmess = "aoOtTCF",
    showmode = false,
    sidescrolloff = 8,
    signcolumn = "yes",
    smartcase = true,
    smartindent = true,
    -- smoothscroll = true,
    -- spell = true,
    splitbelow = true,
    splitkeep = "screen",
    splitright = true,
    tabstop = 4,
    termguicolors = true,
    timeoutlen = 300,
    undofile = true,
    wildmode = "longest:full,full",
    winminwidth = 5,
    wrap = false,
}
do vim.opt[key] = val end
